type Employee{
    firstName:String
    lastName:String
    designation:String
    city:String
}

type Query{
    employee:Employee
}
type Mutation{
    addEmployee(firstName:String,lastName:String,designation:String,city:String):Employee
}